title: Amaury Souza 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 
  Profissional com formação em Dev e com forte atuação em atividades voltadas à Ops há mais de 7 anos. Bacharel em Análise de Sistemas, ce  rtificado em Administração Linux pelo Linux Professional Institute e CompTIA.
  <br><br>
  sddsdsdsdssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  <br><br>
  <a href="https://www.linkedin.com/in/amaurybsouza/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
