title: Amaury Souza # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Profissional com formação em Dev e com forte atuação em atividades voltadas à Ops há mais de 7 anos. Bacharel em Análise de Sistemas, certificado em Administração Linux pelo Linux Professional Institute e CompTIA. Participação ativa na comunidade open-source, com mais de 45 artigos publicados (Medium, Linkedin e nos portais Vivaolinux e Sejalivre.org), 9 scripts (Bash) publicados e colaboração em meetups e grupos no Slack (Linux, Ansible, Terraform, Docker, Zabbix) e no Github contribuindo com PR's e correção de issues em projetos de DevOps. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
